// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger Example",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/api/",
  "paths": {
    "/v1/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Создание нового пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "запрос на создание пользователя",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User successfully created",
            "schema": {
              "$ref": "#/definitions/CreateUserResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "409": {
            "description": "User already exists",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/v1/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Создание нового пользователя",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully created",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Обновление пользователя",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "запрос на обновление пользователя",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully updated",
            "schema": {
              "$ref": "#/definitions/UpdateUserResponse"
            }
          },
          "204": {
            "description": "No content",
            "schema": {
              "type": "object"
            }
          },
          "403": {
            "description": "Forrbidden",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Удаление пользователя",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully deleted",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            }
          },
          "204": {
            "description": "No content",
            "schema": {
              "type": "object"
            }
          },
          "403": {
            "description": "Forrbidden",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateUserRequest": {
      "type": "object",
      "required": [
        "name",
        "email",
        "password"
      ],
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "name": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "CreateUserResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        }
      }
    },
    "ErrorMessage": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetUserResponse": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "user123"
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "name": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "UpdateUserResponse": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "user123"
        }
      }
    }
  },
  "tags": [
    {
      "name": "user"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger Example",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/api/",
  "paths": {
    "/v1/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Создание нового пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "запрос на создание пользователя",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User successfully created",
            "schema": {
              "$ref": "#/definitions/CreateUserResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "409": {
            "description": "User already exists",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/v1/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Создание нового пользователя",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully created",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Обновление пользователя",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "запрос на обновление пользователя",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully updated",
            "schema": {
              "$ref": "#/definitions/UpdateUserResponse"
            }
          },
          "204": {
            "description": "No content",
            "schema": {
              "type": "object"
            }
          },
          "403": {
            "description": "Forrbidden",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Удаление пользователя",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "description": "id пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User successfully deleted",
            "schema": {
              "$ref": "#/definitions/GetUserResponse"
            }
          },
          "204": {
            "description": "No content",
            "schema": {
              "type": "object"
            }
          },
          "403": {
            "description": "Forrbidden",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateUserRequest": {
      "type": "object",
      "required": [
        "name",
        "email",
        "password"
      ],
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "name": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "CreateUserResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        }
      }
    },
    "ErrorMessage": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetUserResponse": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "user123"
        }
      }
    },
    "UpdateUserRequest": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "name": {
          "type": "string",
          "example": "user123"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "UpdateUserResponse": {
      "type": "object",
      "properties": {
        "avatar_photo_url": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "example": "user123@mail.ru"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "user123"
        }
      }
    }
  },
  "tags": [
    {
      "name": "user"
    }
  ]
}`))
}
