version: '3.8'
services:
  gateway-dekstop:
    build:
      context: ./services/gateway-dekstop
    ports:
      - "8080:8080"
    restart: always
  
  gateway-mobile:
    build:
      context: ./services/gateway-mobile
    ports:
      - "8081:8080"
    restart: always     
  gateway-server:
    build:
      context: ./services/gateway-server
    ports:
      - "8081:8080"
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always